apiVersion: apps/v1 
kind: Deployment
metadata:
  name: client-deploy
  namespace: test
  label:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: client-image:latest
        env:
        - name: ServerHeadlessSvc
          value: "server-headless-svc"
        - name: ServerPort
          value: "3654"
        - name: ServerSvc
          value: "server-svc"
        - name: ServerRabbitMQSvc
          value: "server-svc"
        - name: ServerRabbitMQPort
          value: "5672"
        - name: ServerGRPCPort
          value: "50051"
        ports:
        - containerPort: 3317
        resources:
          limits:
            cpu: "1"
            mem: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: test
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
  - name: client-port
    protocol: TCP
    port: 3317
    targetPort: 3317
