apiVersion: apps/v1 
kind: Deployment
metadata:
  name: server-deploy
  namespace: test
spec:
  selector:
    matchLabels:
      app: server
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server-image:latest
        env: 
          - name: ServerRabbitMQSvc
            value: "rabbit-mq-svc"
          - name: ServerRabbitMQPort
            value: "5672"
          - name: ServerKafkaSvc
            value: "kafka-svc"
          - name: ServerKafkaPort
            value: 9092
        ports:
        - containerPort: 3654
        - containerPort: 50051
        resources:
          limits:
            cpu: "1"
            mem: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: server-headless-svc
  namespace: test
spec:
  clusterIP: None
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3654
      targetPort: 3654
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - name: server-port
      protocol: TCP
      port: 3654
      targetPort: 3654
    - name: server-grpc-port
      protocol: TCP
      port: 50051
      targetPort: 50051

