apiVersion: apps/v1 
kind: Deployment
metadata:
  name: server-deploy
  namespace: test
spec:
  selector:
    matchLabels:
      app: server
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server-image:latest
        ports:
        - containerPort: 3654
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: server-headless-svc
  namespace: test
spec:
  clusterIP: None
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3654
      targetPort: 3654
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: test
spec:
  type: ClusterIP
  externalIPs:
    - 10.55.110.176
  selector:
    app: server
  ports:
    - name: server-port
      protocol: TCP
      port: 3654
      targetPort: 3654
    - name: server-grpc-port
      protocol: TCP
      port: 50051
      targetPort: 50051

