apiVersion: apps/v1 
kind: Deployment
metadata:
  name: server-deploy
  namespace: test
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: test
        ports:
        - containerPort: 3654
---
apiVersion: v1
kind: Service
metadata:
  name: server-headless-svc
  namespace: test
spec:
  clusterIP: None
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3654
      targetPort: 3654